version: '3'

services:
    db:
        image: postgres
        ports: 
            - "5432"
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres

    web:
        build: .
        #command: python mysite/manage.py runserver 0.0.0.0:9000
        command: sh -c "./wait-for-it.sh db:3306; python3 mysite/manage.py runserver 0.0.0.0:9000"
        volumes:
             - .:/code
        ports:
            - "9000:9000"
        depends_on:
            - db

